### ISSUE TITLE
SUGGESTION: Ability to set language of stopwords 

### ISSUE THREAD

**Issue by twakawl** [bhumitattarde/WhatsChart#1]
Currently ‘Remove stopwords’ only deletes the English stopwords. Would be great if the user can define the language or languages of which the stopwords will be deleted. In my case it is Dutch and we also use a lot of English.

**Comment by bhumitattarde** [comment]
Hey @twakawl,

It is possible to declare language for removing stopwords. That is what `language of conversation` refers to. It has Dutch as well! 

That being said, multiple languages isn't possible because the library used for removing stop-words doesn't support it itself.
